version: "2"
services:
  londonbus-proxy:
    image: freundallein/londonbus-proxy
    container_name: londonbus-proxy
    command: python main.py
    volumes:
      - ./:/srv/src
      - ./config:/srv/config
    network_mode: "host"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: nginx-debug -g 'daemon off;'
    network_mode: "host"